version: "3"
services:
  api:
    build: TodoApi
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - database
  app:
    build: TodoApp
    ports:
      - "4200:80"
    depends_on:
      - api

  database:
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data
      # - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: passW0rd
volumes:
  postgresql:
