version: "3"
services:
  api:
    build: TodoApi
    ports:
      - "5000:80"
    depends_on:
      - database
    networks:
      - front-end
      - back-end

  app:
    build: TodoApp
    ports:
      - "4200:80"
    depends_on:
      - api
    networks:
      - front-end

  database:
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: passW0rd
    networks:
      - back-end

volumes:
  postgresql:

networks:
  front-end:
  back-end:
