version: "3"
services:
  api:
    build: TodoApi
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
  app:
    build: TodoApp
    ports:
      - "4200:80"
    depends_on:
      - api
